15-Intro-To-Rails/instruments_rails/config/routes.rb
Rails.application.routes.draw do
  resources :instruments, only: [:index]
  # get "/instruments", to: "instruments#index"
  get "/instruments/:id", to: "instruments#show", as: "instrument"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

15-Intro-To-Rails/instruments_rails/app/models/instrument.rb
class Instrument < ApplicationRecord
end

15-Intro-To-Rails/instruments_rails/app/controllers/instruments_controller.rb
class InstrumentsController < ApplicationController

  def index
    @instruments = Instrument.all
    render :index
  end

  def show
    @instrument = Instrument.find(params[:id])
    # render :show
  end

end

15-Intro-To-Rails/instruments_rails/app/helpers/instruments_helper.rb
module InstrumentsHelper
end

15-Intro-To-Rails/instruments_rails/app/views/instruments/index.html.erb
Hello!
<% @instruments.each do |inst| %>
  <%= link_to inst.name, inst %>
  <%# link_to inst.name, instrument_path(inst)  %>
<% end %>

15-Intro-To-Rails/instruments_rails/app/views/instruments/show.html.erb
<h1>
  Name: <%= @instrument.name %>
</h1>
<h2>
  Brand: <%= @instrument.brand %>
</h2>


<%= link_to "Show All Instruments", instruments_path %>

15-Intro-To-Rails/instruments_rails/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>InstrumentsRails</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>