16-rails-forms/dog-tracker/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :dogs, only: [:show, :index, :new, :create, :edit, :update, :destroy]
end

16-rails-forms/dog-tracker/app/models/cat.rb
class Cat < ApplicationRecord

end

16-rails-forms/dog-tracker/app/models/dog.rb
class Dog < ApplicationRecord

end

16-rails-forms/dog-tracker/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  protect_from_forgery
end

16-rails-forms/dog-tracker/app/controllers/dogs_controller.rb
class DogsController < ApplicationController

  before_action :get_dog_by_id, only: [:show, :edit, :update, :destroy]
  
  def index
    @dogs = Dog.all
  end

  def show
  end

  def new
    @dog = Dog.new
  end

  def create
    @dog = Dog.create(dog_params)
    # redirect new_dog_path
    # redirect_to dog_path(@dog.id)
    # redirect_to dog_path(@dog)
    redirect_to @dog
  end


  def edit
  end

  def update
    @dog.update(dog_params)
    redirect_to @dog
  end

  def destroy
    @dog.destroy
    redirect_to dogs_path
  end

  private

  def get_dog_by_id
    @dog = Dog.find(params[:id])
  end

  def dog_params
    params.require(:dog).permit(:name, :tail_length, :color_hexadecimal)
  end

end

16-rails-forms/dog-tracker/app/views/dogs/edit.erb
<%= form_for @dog do |form| %>

  <ul>
    <li>
      <%= form.label :name %>
      <%= form.text_field :name %>
    </li>
    <li>
      <%= form.label :tail_length %>
      <%= form.number_field :"tail_length" %>
    </li>
    <li>
      <%= form.label :color_hexadecimal %>
      <%= form.text_field :color_hexadecimal %>
    </li>
  </ul>

  <%= form.submit %>
<% end %>

16-rails-forms/dog-tracker/app/views/dogs/index.erb
<h1>All the dogs</h1>
<ul>
  <% @dogs.each do |dog| %>
  <li>
    <%= link_to dog.name, dog %>
  </li>
  <% end %>
</ul>

16-rails-forms/dog-tracker/app/views/dogs/new.erb
<%= form_for @dog do |form| %>

  <ul>
    <li>
      <%= form.label :name %>
      <%= form.text_field :name %>
    </li>
    <li>
      <%= form.label :tail_length %>
      <%= form.number_field :"tail_length" %>
    </li>
    <li>
      <%= form.label :color_hexadecimal %>
      <%= form.text_field :color_hexadecimal %>
    </li>
  </ul>

  <%= form.submit %>
<% end %>




<%# form_tag dogs_path, method: "delete" do %>

  <%# label_tag :potato %>
<!--   <ul>
    <li>
      <%= label_tag :name %>
      <%= text_field_tag :name %>
    </li>
    <li>
      <%= label_tag :tail_length %>
      <%= number_field_tag :tail_length %>
    </li>
  </ul>

  <%= submit_tag "Create Dog" %> -->

<%# end %>


<!-- 
<form action="/dogs" method="POST">
  
  <label for="dog-name">Name:</label>
  <input id="dog-name" type="text" />

  <input type="submit" />

</form>
 -->

16-rails-forms/dog-tracker/app/views/dogs/show.erb
<h1><%= @dog.name %></h1>

<ol>
  <li>
Tail Length: <%= pluralize(@dog.tail_length, "foot", "feet") %>
</li>
<li>
Color: <span class="swatch" style="background-color: <%= @dog.color_hexadecimal %>;"></span>
</li>
</ol>

<%= link_to "Edit #{ @dog.name }", edit_dog_path(@dog) %>
<%= form_for @dog, method: :delete do |form| %>
  <%= form.submit "Send #{ @dog.name } to live on a farm" %>
<% end %>

16-rails-forms/dog-tracker/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DogTracker</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>