20-auth/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :colors, only: [:index] do
    resources :votes, only: [:create]
  end

  resources :votes, only: [:index, :destroy]

  resources :users, only: [:new, :create]
  resources :login, only: [:new, :create]
  delete "login", to: "login#destroy", as: "logout"

  root "colors#index"
end

20-auth/app/models/color.rb
class Color < ApplicationRecord
  has_many :votes
end

20-auth/app/models/user.rb
class User < ApplicationRecord

  has_secure_password
  validates_uniqueness_of :username
  has_many :votes

  def remaining_votes
    5 - self.votes.count
  end

  def can_vote?
    self.remaining_votes > 0
  end


  # def password=(value)
  #   self.password_digest = BCrypt::Password.create(value)
  # end

  # def authenticate(plaintext_password)
  #   BCrypt::Password.new(self.password_digest) == plaintext_password
  # end

end

20-auth/app/models/vote.rb
class Vote < ApplicationRecord
  belongs_to :color
  belongs_to :user
end

20-auth/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  skip_before_action :verify_authenticity_token

  before_action :setup_voting_stuff

  def setup_voting_stuff
    @notification = flash["notification"]
    @errors = flash["errors"]

    @user_id = session[:user_id]
    @logged_in = !!@user_id
    if @logged_in
      @logged_in_user = User.find(@user_id)
    end
  end

  def log_out
    session[:user_id] = nil
  end
  
end

20-auth/app/controllers/colors_controller.rb
class ColorsController < ApplicationController


  def index
    if request.path != colors_path
      redirect_to colors_path
    end
    @colors = Color.includes(:votes).all
  end



end

20-auth/app/controllers/login_controller.rb
class LoginController < ApplicationController

  def new
  end

  def create
    @user = User.find_by(username: params[:username])
    if @user && @user.authenticate(params[:password])
      session[:user_id] = @user.id
      redirect_to colors_path
    else
      flash["errors"] = ["Your username or password was incorrect"]
      redirect_to new_login_path
    end
  end

  def destroy
    log_out
    redirect_to colors_path
  end

end

20-auth/app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.create(user_params)
    if @user.valid?
      session[:user_id] = @user.id
      redirect_to colors_path
    else
      flash[:errors] = @user.errors.full_messages
      redirect_to new_user_path
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :password)
  end

end

20-auth/app/controllers/votes_controller.rb
class VotesController < ApplicationController

  def index
    @votes = Vote.all
  end

  def create
    unless @logged_in
      redirect_to new_login_path
      return
    end
    if @logged_in_user.can_vote?
      @vote = Vote.create(color_id: params[:color_id], user_id: @logged_in_user.id)
      flash["notification"] = "You just voted for ##{ @vote.color.hex }"
    else
      flash["errors"] = ["You don't have any votes left 💁‍♀️"]
    end
    redirect_to colors_path
  end

  def destroy
    @vote = Vote.find(params[:id])
    if @logged_in_user.id == @vote.user_id
      @vote.destroy
    end
    redirect_to votes_path
  end

end

20-auth/app/helpers/application_helper.rb
module ApplicationHelper
end

20-auth/app/views/colors/index.erb
<ul class="colors">
  <% @colors.each do |color| %>
  <li class="color" style="background-color: #<%= color.hex %>;">
    #<%= color.hex %>
    <span class="votes">Votes: <%= color.votes.length %>
      <%= form_for [color, Vote.new], local: true do |f| %>
      <button type="submit" class="<%= @logged_in_user && @logged_in_user.can_vote? ? "vote" : "nope" %>">
        <span class="vote">🗳</span>
        <span class="nope">🙅‍♀️</span>
      </button>
      <% end %>
    </span>
  </li>
  <% end %>
</ul>

20-auth/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Favorite colors</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <% if @logged_in %>
        Logged in as <%= @logged_in_user.username %>
        <%= button_to "logout", logout_path, method: :delete %>
        <%# link_to "logout", logout_path, method: :delete %>
      <% else %>
        <%= link_to "Sign up", new_user_path %>
        <%= link_to "Log in", new_login_path %>
      <% end %>
      <% if @notification %>
        <p class="message">
          <%= @notification %>
        </p>
      <% end %>
      <% if @errors && @errors.any? %>
      <ul class="errors">
        <% @errors.each do |error| %>
        <li>
          <%= error %>
        </li>
        <% end %>
      </ul>
      <% end %>
      <% if @logged_in_user %>
      <h2>Votes remaining: <%= @logged_in_user.remaining_votes %></h2>
      <% end %>
    </header>
    <%= yield %>
  </body>
</html>

20-auth/app/views/login/new.erb
<%= form_tag login_index_path do %>
  <ul>
    <li>
      <%= label_tag :username %>
      <%= text_field_tag :username %>
    </li>
    <li>
      <%= label_tag :password %>
      <%= password_field_tag :password %>
    </li>
  </ul>
  <%= submit_tag "Log in" %>
<% end %>

20-auth/app/views/users/new.erb
<%= form_for @user do |f| %>
  <ul>
    <li>
      <%= f.label :username %>
      <%= f.text_field :username %>
    </li>
    <li>
      <%= f.label :password %>
      <%= f.password_field :password %>
    </li>
  </ul>
  <%= f.submit %>
<% end %>

20-auth/app/views/votes/index.erb
<ul>
  <% @votes.each do |vote| %>
  <li class="vote">
    <%= vote.color.hex %>
    <%= vote.user.username %>
    <% if vote.user_id == @user_id %>
      <%= form_for vote, method: :delete do |f| %>
        <%= f.submit "delete" %>
      <% end %>
    <% end %>
  </li>
  <% end %>
</ul>